//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectShopLaptop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_KhuyenMai
    {
        public int KhuyenMaiID { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    }
}
