//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectShopLaptop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        public Tbl_User()
        {
            this.Tbl_ShippingDetails = new HashSet<Tbl_ShippingDetails>();
            this.Tbl_Bill = new HashSet<Tbl_Bill>();
        }
    
        public int user_id { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string role { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<Tbl_ShippingDetails> Tbl_ShippingDetails { get; set; }
        public virtual ICollection<Tbl_Bill> Tbl_Bill { get; set; }
    }
}
