//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectShopLaptop.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ThongKe
    {
        public int ProductId { get; set; }
        public string soPhieu { get; set; }
        public string doanhThu { get; set; }
        public Nullable<decimal> Thu { get; set; }
        public Nullable<decimal> Chi { get; set; }
    
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
